repos:
  # SECURITY
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.0
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
  # FORMATTING & MISC
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
      - id: check-yaml
        args: ['--unsafe']
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        entry: bash -c 'codespell "$@" || true' -- # Don't block, just alert
        verbose: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
        files: .*\.(ya?ml|json|md)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          mkdocs.yml|
          )$
  # PYTHON FORMATTING
  - repo: https://github.com/ambv/black
    rev: "22.10.0"
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E203']
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
  # CFN CHECKS & LINTING
  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.71.1 # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: .*\.(ya?ml)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          cdk.json|
          mkdocs.yml|
          orgtool/spec_init_data.sample/\w+.yaml|
          orgtool/spec_init_data.sample/spec.d/\w+.yaml|
          spec_init_data.blank/\w+.yaml|
          spec_init_data.blank/spec.d/\w+.yaml|
          spec_init_data.entity/\w+.yaml|
          spec_init_data.entity/spec.d/\w+.yaml|
          )$
  - repo: https://github.com/stelligent/cfn_nag
    rev: "v0.8.10"
    hooks:
      - id: cfn-nag
        files: .*\.(ya?ml|json)$
        exclude: (?x)^(
          .pre-commit-config.yaml|
          cdk.json|
          mkdocs.yml|
          orgtool/spec_init_data.sample/spec.d/\w+.yaml|
          spec_init_data.blank/spec.d/\w+.yaml|
          spec_init_data.entity/\w+.yaml|
          spec_init_data.entity/spec.d/\w+.yaml|
          )$

