# orgtool Configuration Parameters

# Path to yaml spec files directory.  Any yaml files under this directory
# (recursive) are parsed as spec files.
spec_dir: "--/spec.d"

# An AWS role name which permits cross account access to all accounts.
org_access_role: "--org_access_role--"

# Use an alternate role from master account when setting up a new account.
#org_access_role: OrganizationAccountAccessRole

# AWS account Id for the Organization master account.  This must be in quotes.
master_account_id: "000000000000"

# AWS account Id for the Central Auth account.  This must be in quotes.
# This Central Auth account can be the same as the Master account.
auth_account_id: "000000000000"
